from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QPushButton,
                             QLabel, QGroupBox, QButtonGroup,QRadioButton, QSpinBox)
window = QWidget()
menu_btn = QPushButton("Menu")
rest_btn = QPushButton("Rest")
next_btn = QPushButton("Answer")

rb_ans1 = QRadioButton("1")
rb_ans2 = QRadioButton("2")
rb_ans3 = QRadioButton("3")
rb_ans4 = QRadioButton("4")

radioGroup = QButtonGroup()
radioGroup.addButton(rb_ans1)
radioGroup.addButton(rb_ans2)
radioGroup.addButton(rb_ans3)
radioGroup.addButton(rb_ans4)

lb_question = QLabel("Question")
lb_rest = QLabel("min")
lb_result = QLabel("Correct")
lb_right_ans = QLabel("Answer")

sp_rest = QSpinBox()
gb_question = QGroupBox("Answer variants")
gb_answer = QGroupBox()

rb_v1 = QVBoxLayout()
rb_v2 = QVBoxLayout()
rb_h1 = QHBoxLayout()
rb_v1.addWidget(rb_ans1)
rb_v1.addWidget(rb_ans2)
rb_v2.addWidget(rb_ans3)
rb_v2.addWidget(rb_ans4)
rb_h1.addLayout(rb_v1)
rb_h1.addLayout(rb_v2)
gb_question.setLayout(rb_h1)

v1 = QVBoxLayout()
v1.addWidget(lb_result)
v1.addWidget(lb_right_ans)
gb_answer.setLayout(v1)

h1 = QHBoxLayout()
h2 = QHBoxLayout()
h3 = QHBoxLayout()
h4 = QHBoxLayout()
v1_main = QVBoxLayout()
h1.addWidget(menu_btn)
h1.addStretch(1)
h1.addWidget(rest_btn)
h1.addWidget(sp_rest)
h1.addWidget(lb_rest)
h2.addWidget(lb_question, alignment = (Qt.AlignHCenter | Qt.AlignVCenter))
h3.addWidget(gb_question)
h3.addWidget(gb_answer)
gb_answer.hide()
h4.addStretch(1)
h4.addWidget(next_btn, stretch=2)
h4.addStretch(1)
v1_main.addLayout(h1, stretch=1)
v1_main.addLayout(h2, stretch=2)
v1_main.addLayout(h3, stretch=8)
v1_main.addLayout(h4)
v1_main.setSpacing(5)
window.setLayout(v1_main)
window.resize(550, 450)
